### ISSUE TITLE
[REQUEST] Add Virtual Keyboard support!

### ISSUE THREAD

**Issue by bolsoncerrado** [OctoPrint/OctoPrint-ForceLogin#1]
Howdy!

Long time Octoprint+Touch user here, installed 1.3.10 and now the nice FORCE LOGIN plugin comes preinstalled and asking login/password, which works great when accessing from desktop computers but its rejecting to show the virtual keyboard we have installed in the local Rapsi/Touch screen, hence we can't log in locally.

Any way to call the virtual keyboard back? 

Touching the input fields seems not to call the keyboard at all.

**Comment by foosel** [comment]
As the plugin is now bundled (and the bundled version works completely different internally than what's kept here for historical purposes), please open this on the [OctoPrint bug tracker](https://github.com/foosel/OctoPrint/issues).

For the record though, I have no idea why the virtual keyboard isn't showing, the plugin simply contains your run-of-the-mill input fields.
